import { makeStyles, shorthands } from "@griffel/react";
import { COLOR } from "./color.style";

export const useClasses = makeStyles({
    container: {
        position: "relative",
        display: "flex",
        flexDirection: "column",
        boxSizing: "border-box",
        ...shorthands.margin("1rem"),
        backgroundColor: COLOR.acrylicBackgroundBase,
        ...shorthands.border("0.1rem", "solid", COLOR.surfaceStrokeDefault),
        ...shorthands.borderRadius("0.7rem"),
        boxShadow: `0rem 0rem 1rem ${COLOR.smokeBackgroundDefault}`,
    },
    leftEdgeContainer: {
        flexDirection: "row-reverse",
        minWidth: "6.8rem",
        backgroundColor: "transparent",
        ...shorthands.borderRadius(
            "0rem /* @noflip */",
            "0.7rem /* @noflip */",
            "0.7rem /* @noflip */",
            "0rem /* @noflip */",
        ),
        ...shorthands.border("0rem"),
        boxShadow: "none",
    },
    rightEdgeContainer: {
        flexDirection: "row",
        minWidth: "6.8rem",
        backgroundColor: "transparent",
        ...shorthands.borderRadius(
            "0.7rem /* @noflip */",
            "0rem /* @noflip */",
            "0rem /* @noflip */",
            "0.7rem /* @noflip */",
        ),
        ...shorthands.border("0rem"),
        boxShadow: "none",
    },
    containerHorizontalExpand: {
        backgroundColor: COLOR.acrylicBackgroundBase,
        minHeight: "36.5rem",
        boxShadow: `0rem 0rem 1rem ${COLOR.smokeBackgroundDefault}`,
    },
    containerVerticalExpand: {
        backgroundColor: COLOR.acrylicBackgroundBase,
        minHeight: "25.6rem",
        boxShadow: `0rem 0rem 1rem ${COLOR.smokeBackgroundDefault} /* @noflip */`,
    },
    containerTopEdgeExpand: {
        backgroundColor: COLOR.acrylicBackgroundBase,
        minHeight: "36.5rem",
        boxShadow: `0rem 0rem 1rem ${COLOR.smokeBackgroundDefault}`,
    },
    containerTransparent: {
        opacity: 0.4,
    },
    containerTempHide: {
        opacity: 0.01,
    },
    mainContainer: {
        boxSizing: "border-box",
        display: "flex",
        flexShrink: 0,
        flexDirection: "row",
        order: 2,
        alignItems: "stretch",
        ...shorthands.margin("0rem", "0.6rem"),
    },
    topMainContainer: {
        order: 1,
    },
    topEdgeMainContainer: {
        paddingTop: "0.4rem",
        order: 1,
    },
    leftEdgeMainContainer: {
        width: "5.7rem",
        ...shorthands.borderTop("0.1rem", "solid", COLOR.surfaceStrokeDefault),
        ...shorthands.borderBottom("0.1rem", "solid", COLOR.surfaceStrokeDefault),
        boxShadow: `0rem 0rem 1rem ${COLOR.smokeBackgroundDefault} /* @noflip */`,
        flexDirection: "column",
        backgroundColor: COLOR.acrylicBackgroundBase,
        order: 3,
        ...shorthands.padding("0.6rem", "0rem"),
        ...shorthands.margin("0rem"),
    },
    rightEdgeMainContainer: {
        width: "5.7rem",
        ...shorthands.borderTop("0.1rem", "solid", COLOR.surfaceStrokeDefault),
        ...shorthands.borderBottom("0.1rem", "solid", COLOR.surfaceStrokeDefault),
        boxShadow: `0.5rem 0.5rem 1rem -0.5rem ${COLOR.smokeBackgroundDefault} /* @noflip */
            , 0.5rem -0.5rem 1rem -0.5rem ${COLOR.smokeBackgroundDefault} /* @noflip */`,
        flexDirection: "column",
        backgroundColor: COLOR.acrylicBackgroundBase,
        order: 3,
        ...shorthands.padding("0.6rem", "0rem"),
        ...shorthands.margin("0rem"),
    },
    mainContainerRightExpand: {
        ...shorthands.padding(
            "0.6rem",
            "0rem /* @noflip */",
            "0.6rem",
            "0rem /* @noflip */",
        ),
        boxShadow: "none",
    },
    mainContainerLeftExpand: {
        ...shorthands.padding(
            "0.6rem",
            "0rem /* @noflip */",
            "0.6rem",
            "0rem /* @noflip */",
        ),
        boxShadow: "none",
    },
    miniToolContainer: {
        width: "calc(100% - 12.4rem)",
        marginTop: "1rem",
        marginBottom: "1rem",
        marginRight: "0.1rem",
    },
    rightEdgeMiniToolContainer: {
        width: "3.6rem",
        marginTop: "0rem",
        marginBottom: "0rem",
        marginLeft: "1rem /* @noflip */",
    },
    leftEdgeMiniToolContainer: {
        width: "3.6rem",
        marginTop: "0rem",
        marginBottom: "0rem",
        marginLeft: "1rem /* @noflip */",
    },
    topToolListContainer: {
        flexGrow: 1,
        maxHeight: "32.2rem",
        ...shorthands.borderTop("0.1rem", "solid", COLOR.controlStrokeDefault),
        ...shorthands.borderRadius("0rem", "0rem", "0.7rem", "0.7rem"),
        backgroundColor: COLOR.layerDefault,
        width: "100%",
        order: 3,
        overflowY: "auto",
    },
    bottomToolListContainer: {
        flexGrow: 1,
        maxHeight: "31.6rem",
        ...shorthands.borderBottom("0.1rem", "solid", COLOR.controlStrokeDefault),
        backgroundColor: COLOR.layerDefault,
        marginBottom: "0.4rem",
        width: "100%",
        order: 1,
        overflowY: "auto",
    },
    topEdgeToolListContainer: {
        flexGrow: 1,
        maxHeight: "31.9rem",
        ...shorthands.borderTop("0.1rem", "solid", COLOR.controlStrokeDefault),
        backgroundColor: COLOR.layerDefault,
        width: "100%",
        order: 3,
        overflowY: "auto",
    },
    showSearchBoxToolListContainer: {
        maxHeight: "32.2rem",
    },
    showSearchBoxBottomToolListContainer: {
        maxHeight: "31.6rem",
    },
    showSearchBoxTopEdgeToolListContainer: {
        maxHeight: "31.9rem",
    },
    leftEdgeToolListContainer: {
        ...shorthands.borderTop("0.1rem", "solid", COLOR.surfaceStrokeDefault),
        ...shorthands.borderBottom("0.1rem", "solid", COLOR.surfaceStrokeDefault),
        ...shorthands.borderLeft(
            "0.1rem /* @noflip */",
            "solid /* @noflip */",
            ` ${COLOR.controlStrokeDefault} /* @noflip */`,
        ),
        ...shorthands.borderRight("0rem"),
        backgroundColor: COLOR.layerDefault,
        width: "calc(100% - 6.9rem)",
        boxSizing: "border-box",
        order: 1,
    },
    rightEdgeToolListContainer: {
        ...shorthands.borderTop("0.1rem", "solid", COLOR.surfaceStrokeDefault),
        ...shorthands.borderBottom("0.1rem", "solid", COLOR.surfaceStrokeDefault),
        ...shorthands.borderRight(
            "0.1rem /* @noflip */",
            "solid /* @noflip */",
            ` ${COLOR.controlStrokeDefault} /* @noflip */`,
        ),
        ...shorthands.borderLeft("0rem"),
        backgroundColor: COLOR.layerDefault,
        width: "calc(100% - 6.9rem)",
        boxSizing: "border-box",
        order: 1,
    },
});
